---
cilium_tetragon_namespace: kube-system
cilium_tetragon_chart_version: "1.3.0"
cilium_tetragon_helm_repo: "https://helm.cilium.io/"
cilium_tetragon_helm_release_name: tetragon
cilium_tetragon_baseline_policies_enabled: true
cilium_tetragon_kubeconfig: "{{ lookup('env', 'KUBECONFIG') | default('~/.kube/config', true) }}"
cilium_tetragon_context: ""
cilium_tetragon_wait: true
cilium_tetragon_wait_timeout: 300
cilium_tetragon_state: present
